#!/bin/bash

DAEMON=/usr/bin/python
ARGS=/home/pi/CEIT_Temperature/lib_temp.py 301
PIDFILE=/var/run/lib_temp.pid

case "$1" in
  start)
    echo "Starting server"
    /sbin/start-stop-daemon --start --pidfile $PIDFILE \
        -b --make-pidfile \
        --exec $DAEMON $ARGS
    ;;
  stop)
    echo "Stopping lib_temp"
    /sbin/start-stop-daemon --stop --pidfile $PIDFILE --verbose
    ;;
  *)
    echo "Usage: /etc/init.d/lib_temp {start|stop}"
    exit 1
    ;;
esac

exit 0
